version: "3.9"

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - micro-net

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"  # management UI
  #   networks:
  #     - micro-net

  user-service:
    build: ./userService
    container_name: user-service
    ports:
      - "4001:4001"
    environment:
    - JWT_SECRET=mySuperSecretKey
    depends_on:
      - mongo
    networks:
      - micro-net

  product-service:
    build: ./productService
    container_name: product-service
    ports:
      - "4002:4002"
    environment:
    - JWT_SECRET=mySuperSecretKey
    depends_on:
      - mongo
    networks:
      - micro-net

  order-service:
    build: ./orderService
    container_name: order-service
    ports:
      - "4003:4003"
    environment:
    - JWT_SECRET=mySuperSecretKey
    depends_on:
      - mongo
    networks:
      - micro-net

  # inventory-service:
  #   build: ./inventoryService
  #   container_name: inventory-service
  #   depends_on:
  #     - mongo
  #   networks:
  #     - micro-net

  # notification-service:
  #   build: ./notificationService
  #   container_name: notification-service
  #   networks:
  #     - micro-net

networks:
  micro-net:
    driver: bridge
